Revised README
jennyengelman/PongMates pull request #61
Opened 2018-04-18 14:22 UTC by jennyengelman

Changed PongMates to Need One
Updated and Elaborated Architecture section

2018-04-18 21:07 UTC, ijemmao requested changes
Solid README

2018-04-18 21:07 UTC, ijemmao commented on README.md
> +We'd like to thank our faculty advisor Lorie Loeb and mentor Ijemma Onwuzulike (Dartmouth class of ‘19) for their guidance and the hard work they've contributed to helping us succeed in achieving our
I would change the double dash (--) to just commas

2018-04-18 21:07 UTC, ijemmao commented on README.md
> +- Expo is a tool for React Native applications that, by providing a prototype formate, aided our development process.
formate to format

2018-04-19 00:12 UTC, jennyengelman commented
Were these the formatting changes you wanted?

2018-04-19 01:08 UTC, merged